### ISSUE TITLE
Unrecognized option error

### ISSUE THREAD

**Issue by Denspa** [tribbloid/ISpark#10]
Hi,

I'm getting an urecognized option error.

Spark assembly has been built with Hive, including Datanucleus jars on classpath
Error: Unrecognized option '--profile'.

It seems the options aren't being passed to the Main class, instead they are being passed to the Spark submit as arguments.

Have you noticed this before? I'm sure I'm doing something completely boneheaded here.

My profile file looks like :

import os
c = get_config()
SPARK_HOME = os.environ['SPARK_HOME']

MASTER = 'yarn'

c.KernelManager.kernel_cmd = [SPARK_HOME+"/bin/spark-submit",
 "--master", MASTER,
 "--executor-memory", "2G",
 "--class", "org.tribbloid.ispark.Main",
 "--jars", "/ISpark/core/target/ispark-core-0.2.0-SNAPSHOT",
 "--profile", "{connection_file}",
 "--interp", "Spark",
 "--parent"]

c.NotebookApp.ip = '0.0.0.0'
c.NotebookApp.open_browser = False
c.NotebookApp.port = 8888

**Comment by tribbloid** [comment]
The only problem I see so far is the outdated --interp option.
This is the profile I'm using and it is functioning properly

c.KernelManager.kernel_cmd = [SPARK_HOME+"/bin/spark-submit",
 "--master", MASTER,
 "--class", "org.tribbloid.ispark.Main",
 "--executor-memory", "2G",
 "--jars", GIT_HOME+"/ISpark-server/core/target/scala-2.10/ispark-core-assembly-0.2.0-SNAPSHOT.jar",
 "--profile", "{connection_file}",
 "--parent"]

**Comment by tribbloid** [comment]
hey buddy can you confirm that your environment can run it? I think this is no longer a problem and should be closed in 2 weeks

**Comment by Denspa** [comment]
Hi,

I upgraded to ipython 3 and I don't face the same issue now. I now get:
Exception in thread "main" java.lang.NoClassDefFoundError: play/api/libs/json/Reads

probably a missing dependency. I'll try and see if I can figure it out tomorrow.

Thank you for following up.

**Comment by tribbloid** [comment]
Interesting, another guy reports the same error on ipython2, he was using Spark on Scala 2.11, after switching back to 2.10 the error vanished.
I'm afraid I still need some time to port it to Scala 2.11 at the moment. Their REPLs are very different

**Comment by Denspa** [comment]
Thanks for the tip. Searching through the other issue I found that you had pre-built the jars. Using the release jar worked. Closing this issue.

**Comment by Denspa** [comment]
I removed Scala 2.11 but I still faced the same issue with the jars I try and build myself.

[WARNING]  org.scalatest:scalatest_2.10:2.2.4 requires scala version: 2.10.4
[WARNING]  org.scala-lang:scala-reflect:2.10.4 requires scala version: 2.10.4
[WARNING]  com.twitter:chill_2.10:0.5.0 requires scala version: 2.10.4
[WARNING]  org.spark-project.akka:akka-remote_2.10:2.3.4-spark requires scala version: 2.10.4
[WARNING]  org.spark-project.akka:akka-actor_2.10:2.3.4-spark requires scala version: 2.10.4
[WARNING]  org.spark-project.akka:akka-slf4j_2.10:2.3.4-spark requires scala version: 2.10.4
[WARNING]  org.apache.spark:spark-core_2.10:1.3.1 requires scala version: 2.10.4
[WARNING]  org.json4s:json4s-jackson_2.10:3.2.10 requires scala version: 2.10.0

**Comment by tribbloid** [comment]
Are these just warnings? You can safely ignore those, all minor versions are compatible with each others

**Comment by Denspa** [comment]
during the build phase I get these warnings but when I try and use the built jar I get the same error as earlier
Exception in thread "main" java.lang.NoClassDefFoundError: play/api/libs/json/Reads

**Comment by Denspa** [comment]
I was using the wrong jar similar to #5
