### ISSUE TITLE
Task not serializable error with HashingTF

### ISSUE THREAD

**Issue by shasdemir** [tribbloid/ISpark#18]
Hello,

Using org.apache.spark.mllib.feature.HashingTF in an RDD map gives Task Not Serializable error. Code:

import org.apache.spark.mllib.feature.HashingTF

val spamText = sc.textFile(dataLocation)
val tf = new HashingTF(numFeatures = 10000)
val spamFeatures = spamText.map(email => tf.transform(email.split(" ")))

org.apache.spark.SparkException: Task not serializable
    org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:166)
    org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:158)
    org.apache.spark.SparkContext.clean(SparkContext.scala:1605)
    org.apache.spark.rdd.RDD.map(RDD.scala:286)

**Comment by tdna** [comment]
I think that's not the fault of ISpark.
I think if you compile the code and submit you will get the same message.

**Comment by shasdemir** [comment]
The problem does not exist on Zeppelin, though.

**Comment by tribbloid** [comment]
I probably encounter it somewhere else before, could you try:
```
@transient val tf = new HashingTF(numFeatures = 10000)
```
and let me know the result
?

**Comment by shasdemir** [comment]
I tried with the @transient, but I'm getting the same error.

Would you need extra info about my configuration? I can post my ipython_config.py if you want.

**Comment by tribbloid** [comment]
I've tested again on the latest build and didn't see this problem, it may be a bug on 1.3.0 but was resolved 0.0.1 later, I'll upload the latest jar tomorrow.

**Comment by tribbloid** [comment]
New jar and source code uploaded. Please use the following code to test:

import org.apache.spark.mllib.feature.HashingTF
val text ="Apache Spark is an open-source cluster computing framework originally developed in the AMPLab at UC Berkeley. In contrast to Hadoop's two-stage disk-based MapReduce paradigm, Spark's in-memory primitives provide performance up to 100 times faster for certain applications.[1] By allowing user programs to load data into a cluster's memory and query it repeatedly, Spark is well suited to machine learning algorithms.[2]"
val spamText = sc.parallelize(text.split("[\\.,]"))
val tf = new HashingTF(numFeatures = 10000)
val spamFeatures = spamText.map(email => tf.transform(email.split(" ")))
spamFeatures.count()

case closed

**Comment by shasdemir** [comment]
Thank you for the quick fix.
