### ISSUE TITLE
Updgrade to Spark 1.3.0

### ISSUE THREAD

**Issue by FlytxtRnD** [tribbloid/ISpark#8]
Hi,
Is there any plan to upgrade ISpark to spark 1.2 or upcoming spark 1.3 version

**Comment by tribbloid** [comment]
of course, my latest local repo has already been uploaded to 1.2, just hesitating to push because of this issue: https://issues.apache.org/jira/browse/SPARK-4923
It takes some hack to resolve spark-repl 1.2.0 as a dependency. My initial plan was to upgrade after release of spark 1.3.0/1.2.1 or repl 1.2.0 is published retrospectively. What do you think?

**Comment by gianluca-sabena** [comment]
Why don't publish it in a branch of this repo? It's pimplier to publish a jar locally than redo all your good job.... And I could help to test and fix it...

**Comment by FlytxtRnD** [comment]
It would be great if you can  update it  with Spark 1.3.

**Comment by gianluca-sabena** [comment]
I have a production cluster with spark 1.2.0. I suggest to have different branches for relative spark version to have Ispark and Spark aligned

**Comment by tribbloid** [comment]
Hey buddies,

Sorry I was quite stressed this week with some business stuff. I'll 
publish a major update in a few days including some visualization features.

Yours Peng

**Comment by FlytxtRnD** [comment]
Hey , 
Could you please publish the version which can run on spark-1.3 asap, if it is convenient for u?

**Comment by tribbloid** [comment]
Yeah, just give me some time.

This will affect a visualization component for SQL tables, which has 
been renamed to DataFrame in 1.3.0. But in general shouldn't be hard.

Yours Peng

**Comment by FlytxtRnD** [comment]
Thank you so much..

**Comment by tribbloid** [comment]
Done!!!!!!!!!!!!!! please pull from me to use on Spark 1.3.0

**Comment by FlytxtRnD** [comment]
thanks :+1:
